### ISSUE TITLE
Shipping crash

### ISSUE THREAD

**Issue by alefriant** [oculus-samples/Unreal-MRUtilityKitSample#4]
Hey guys!
I downloaded your sample and it packages perfect in development, but when I tried to build it for shipping to try it in the Oculus Store, the build crashes, could you help me with that please?
I tried SharedSpaces with exactly the same settings in UE543-v68 and works perfect in Shipping mode. 

I'm using the Meta-Oculus fork 5.4.3-v100-v68
Settings: SDK/NDK etc. android-32
NDK API 29
(I use the same settings for some games I have in Store or in the App Labs.)

![image](https://github.com/user-attachments/assets/dbc87af6-f903-4d59-bbe4-44c9469e5f76)

Here is the log when it crashes in shipping mode:

13 actionable tasks: 1 executed, 12 up-to-date
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing Z:\AFSProject\app\src\main\AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

> Task :app:ueAFSProjectAssembleRelease FAILED

FAILURE: Build failed with an exception.
80 actionable tasks: 11 executed, 69 up-to-date

* What went wrong:
Execution failed for task ':app:ueAFSProjectAssembleRelease'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s

cmd.exe failed with args /c "F:\Unreal-MRUtilityKitSample-main\Intermediate\Android\arm64\gradle\rungradle.bat" :app:assembleRelease
(see F:\Oculus_UE543\Engine\Programs\AutomationTool\Saved\Logs\Log.txt for full exception trace)

BuildException: cmd.exe failed with args /c "F:\Unreal-MRUtilityKitSample-main\Intermediate\Android\arm64\gradle\rungradle.bat" :app:assembleRelease
   at UnrealBuildTool.UEDeployAndroid.RunCommandLineProgramWithExceptionAndFiltering(String WorkingDirectory, String Command, String Params, ILogger Logger, String OverrideDesc, Boolean bUseShellExecute) in F:\Oculus_UE543\Engine\Source\Programs\UnrealBuildTool\Platform\Android\UEDeployAndroid.cs:line 1935
   at UnrealBuildTool.UEDeployAndroid.MakeApk(AndroidToolChain ToolChain, String ProjectName, TargetType InTargetType, String ProjectDirectory, String OutputPath, String EngineDirectory, Boolean bForDistribution, String CookFlavor, UnrealTargetConfiguration Configuration, Boolean bMakeSeparateApks, Boolean bIncrementalPackage, Boolean bDisallowPackagingDataInApk, Boolean bDisallowExternalFilesDir, Boolean bSkipGradleBuild, Boolean bIsArchive, Boolean bIsFromUAT, Boolean bSkipUECommandLineMatch) in F:\Oculus_UE543\Engine\Source\Programs\UnrealBuildTool\Platform\Android\UEDeployAndroid.cs:line 5248
   at UnrealBuildTool.UEDeployAndroid.PrepForUATPackageOrDeploy(FileReference ProjectFile, String ProjectName, DirectoryReference ProjectDirectory, String ExecutablePath, String EngineDirectory, Boolean bForDistribution, String CookFlavor, UnrealTargetConfiguration Configuration, Boolean bIsDataDeploy, Boolean bSkipGradleBuild, Boolean bIsArchive, Boolean bSkipUECommandLineMatch) in F:\Oculus_UE543\Engine\Source\Programs\UnrealBuildTool\Platform\Android\UEDeployAndroid.cs:line 5874
   at AndroidPlatform.Package(ProjectParams Params, DeploymentContext SC, Int32 WorkingCL) in F:\Oculus_UE543\Engine\Source\Programs\AutomationTool\Android\AndroidPlatform.Automation.cs:line 0
   at AutomationScripts.Project.Package(ProjectParams Params, Int32 WorkingCL) in F:\Oculus_UE543\Engine\Source\Programs\AutomationTool\Scripts\PackageCommand.Automation.cs:line 51
   at BuildCookRun.DoBuildCookRun(ProjectParams Params) in F:\Oculus_UE543\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 237
   at BuildCookRun.ExecuteBuild() in F:\Oculus_UE543\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 43
   at AutomationTool.BuildCommand.Execute() in F:\Oculus_UE543\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 345
   at AutomationTool.BuildCommand.ExecuteAsync() in F:\Oculus_UE543\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 354
   at AutomationTool.Automation.ExecuteAsync(List`1 CommandsToExecute, Dictionary`2 Commands) in F:\Oculus_UE543\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 270
   at AutomationTool.Automation.ProcessAsync(ParsedCommandLine AutomationToolCommandLine, StartupTraceListener StartupListener, HashSet`1 ScriptModuleAssemblies) in F:\Oculus_UE543\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 164

AutomationTool executed for 0h 1m 41s
AutomationTool exiting with ExitCode=1 (Error_Unknown)

**Comment by felixweilbach** [comment]
I can not reproduce your problem.

It looks like the shipping fails because of the AndroidManifest. In the MRUK sample we do not do any changes to the android manifest besides adding the USE_SCENE permission. The Unreal Engine Meta fork which you are using does some changes to the manifest. But I couldn't reproduce your problem with the Unreal Engine fork from Meta. Did you do any changes that could influence the Manifest generation? Is it possible to get a bit more information what exactly failed during parsing of the manifest?

Just for reference this is what I tried to reproduce the problem:

- Clone this repository to my machine
- Clone the Unreal Engine Meta fork to my machine
- Build the MRUtilityKitSample with the Unreal Engine Meta fork
- Select 'Shipping' in the packaging settings and pressed Android -> Package Project.
- This succeeds without any errors.

**Comment by alefriant** [comment]
Hey @felixweilbach 
Seems I had a problem with the manifest. Thanks for your giving me a second opinion with your steps, I started from zero and it works. 

I have another problem now:
Can I remove all the experimental plugins it has enabled? I found a few of them, but no idea which of them are being used, BaseCharacterFXEditor as example, makes reference to ChaosEditor.
It has:
- Control rig modules.
- Dump GPU Services
- MetaHuman Project Utilities
- Tools Preset
- Struc Utilits
- World Metrics.
If I'm not missing any, those are all, all of these experimental which is not functional or too risky to work based on them if they are modified or removed later. 
Suggestions are welcome. Thanks!

![image](https://github.com/user-attachments/assets/257b9e18-5cae-4fbf-b4d1-585ff117e157)

**Comment by felixweilbach** [comment]
It should not have any dependencies to the modules you mentioned, and it shouldn't make use of any experimental APIs from Epic. I will double check that.

**Comment by alefriant** [comment]
Thank you!!

**Comment by felixweilbach** [comment]
I'll close that issue because I think everything was answered. If you think we didn't address everything then feel free to open the issue again.
